### ISSUE TITLE
Use TypeScript for intellisense 

### ISSUE THREAD

**Issue by atsu85** [denofevil/AureliaStorm#10]
With typescript type info from Viewmodel classes it would be possible to suggest in addition to properties and methods of VM class also nested properties and methods of VM class field, such as  `${user.getAddress().city}`

**Comment by atsu85** [comment]
Smth like @MeirionHughes does in aurelia-template-lint. See failure message of test [rejects bad attribute binding to imported type](https://github.com/MeirionHughes/aurelia-template-lint/blob/develop/spec/binding.spec.ts#L348-376) as an example for what i mean.

**Comment by denofevil** [comment]
@atsu85 that thing is already working, non existing fields are highlighted

**Comment by atsu85** [comment]
@denofevil, I didn't see it, but it looks like I'm experiencing [some other issue](https://github.com/denofevil/AureliaStorm/issues/11).
