### ISSUE TITLE
Plugin not working (when using JSPM/Webpack skeleton or Aurelia-CLI to create a project)

### ISSUE THREAD

**Issue by atsu85** [denofevil/AureliaStorm#11]
I've installed AureliaStorm plugin for `IntelliJ IDEA (Ultimate) 2016.2.2`, but I haven't discovered any features that this plugin offers.

I can see it in the list of enabled plugins and there doesn't seem to be any configuration options (note, I'm evaluating IDEA, so I might be missing some basic knowledge of IntelliJ platform).

Is there anything else I need to do, before this plugin becomes useful for my project?

**Comment by denofevil** [comment]
It should provide intellisense in the Aurelia interpolations (completion and navigation with proper context) and understand some of the Aurelia specific tag attributes (bind, trigger, etc., navigation only).
It looks for aurelia-core.js in your project (https://github.com/denofevil/AureliaStorm/blob/master/src/main/kotlin/com/github/denofevil/aurelia/Aurelia.kt#L16), is it there?

**Comment by atsu85** [comment]
Thanks, after adding the empty `aurelia-core.js` file the plugin started working (activated) as expected.

It took me a bit time to figure out why You decided to detect Aurelia project based on presence of `aurelia-core.js` file. It looks like You expect the project to have [simplest possible setup](http://aurelia.io/hub.html#/doc/article/aurelia/framework/latest/quick-start/2) (with `<script src="scripts/aurelia-core.min.js"></script>`), that is almost never used in real projects. Instead of including Aurelia with script tag, "real projects" use either
* module loader (such as SystemJS or RequireJS to load the script into browser) in conjunction with build tools (Gulp transpiles TypeScript/ES7 code with TypeScript or Babel and lints and minifies and bundles the script to be loaded by module loader)
* or module bundler (Webpack - builds, transpiles, minifies, ... and loads bundle into browser)

[Aurelia/skeleton-navigation](https://github.com/aurelia/skeleton-navigation) repository contains subfolders for different combinations of tech stack (language: ESNext or TypeScript; JSPM or Webpack) that could be used with Aurlia (see [skeleton-typescript](https://github.com/aurelia/skeleton-navigation/tree/master/skeleton-typescript)) and none of them contain aurelia-core.js file. Additionally there is [Aurelia-CLI](https://github.com/aurelia/cli), that can be used to kick-start the project by answering the questions related to prefered tech stack (CLI is still in alpha stage, and it uses RequireJS instead of JSPM or Webpack).

**Comment by atsu85** [comment]
@denofevil, I created a [PR](https://github.com/denofevil/AureliaStorm/pull/12) to fix this issue :)

**Comment by denofevil** [comment]
Thank you for the PR, merged!

**Comment by atsu85** [comment]
@denofevil, could You please release/publish the new version - I've created https://github.com/denofevil/AureliaStorm/issues/13 for that
