### ISSUE TITLE
autocomplete methods in attributes with `.call` suffix

### ISSUE THREAD

**Issue by atsu85** [denofevil/AureliaStorm#16]
I've created custom element, that I'm using like this:
`<my-button click.call="someMethod()"></my-button>`

In this case autocomplete in click.call attribute content doesn't suggest methods from viewModel, but when replacing `click.call` with `click.delegate` or `click.trigger`, then autocomplete works as expected.

**Comment by denofevil** [comment]
@atsu85 it can be fixed by adding call to https://github.com/denofevil/AureliaStorm/blob/master/src/main/kotlin/com/github/denofevil/aurelia/Aurelia.kt#L11

**Comment by atsu85** [comment]
Yeah, i saw that, just wanted to file the issue as i don't have time to fix it right now. 

PS. Is this project funded by IntelliJ or is it Your personal hobby project?

**Comment by denofevil** [comment]
@atsu85 I'm doing it in my free time, so I'm having same problem)

**Comment by atsu85** [comment]
That's a shame :( (I mean JetBrains, not You ;) )

Perhaps You can provide an insight, what are the JetBrains plans with Aurelia plugin? JetBrains support (Yaroslav Bedrov) directed me to this plugin, so at least "they" are aware You are working on it. I really hope it will get some attention from JetBrains as well.

**Comment by denofevil** [comment]
I'm WebStorm team lead, so I guess that's quite enough attention :)
Right now the plan is to see how it goes with this plugin and depending on the results we either keep it as it is or dedicate more resources.

**Comment by Turbo87** [comment]
> depending on the results we either keep it as it is or dedicate more resources.

I know I can be annoying and this is slightly off-topic, but are there similar plans for Ember? 😉

**Comment by denofevil** [comment]
Fixed in 0.4
