### ISSUE TITLE
phpstorm reports plugin exception  

### ISSUE THREAD

**Issue by timburrows** [denofevil/AureliaStorm#21]
When editing a javascript file, new or existing:

AssertionError
                After patch: doc:
                'xxx.name'
                ---PSI:
                ''
                ---chars:
                ''.
                Language: JavaScript;
                Host file: HtmlFile:xxx.html in 'xxx/Work/athena/athena-client/src/welcome/home.html'
                Context element (177,262): 'XmlText'; Ranges: [Shred (177,262): XmlText In host range: (231,240); PSI range: (0,0)]

**Comment by pbrickell** [comment]
I'm getting these any time I open an HTML file in the editor. Having to disable the plugin.
