### ISSUE TITLE
Plugin stopped working with the newest version of WebStorm (2016.3)

### ISSUE THREAD

**Issue by lares83** [denofevil/AureliaStorm#25]
Hi,
I've noticed that plugin stopped working with the newest version 2016.3.
With the previous version 2016.2.4 everything worked fine.

**Comment by atsu85** [comment]
@lares83, Jetbrains might take over this plugin if it gains enough attention: https://youtrack.jetbrains.com/issue/WEB-15554
Votes might help :)

**Comment by denofevil** [comment]
@lares83, I've uploaded 0.4 and it works fine with 2016.3 for me. Please let me know if it doesn't for you
