### ISSUE TITLE
Bug: Plugin doesn't work when node_modules are excluded.

### ISSUE THREAD

**Issue by fragsalat** [denofevil/AureliaStorm#26]
Since the aurelia-cli installs a project with the dependency manager npm you will have the aurelia-framework.js file in the node_modules.
IntelliJ excludes this folder per default which absolutely makes sense since there is to much useless code for the index.

So it would be nice if the detection of the framework could be done even if the folder with the aurelia-framework.js or aurelia-core.js is excluded.
Alternatively you could check if there is a aurelia-app tag in the index.html or add an checkbox in the settings to enable aurelia support which get the default value true if one of the files is there.

**Comment by denofevil** [comment]
I've added an aurelia-bootstrapper.js file to the detection list, it's included into the scope for aurelia-cli projects
