### ISSUE TITLE
PhpStorm Aurelia plugin breaks code

### ISSUE THREAD

**Issue by akinofftz** [denofevil/AureliaStorm#30]
I noticed the last days that Aurelia plugin is breaking code on commit by silently replacing code like `${journey.startDate | date:'L' }` by `${journey.startDate | date;:'L' }` which is invalid. There is no workaround than commiting stuff separately from PhpStorm.

**Comment by denofevil** [comment]
@akinofftz I'm sorry for the delayed reply.
Which PhpStorm version are you using? Can you provide a little bit bigger sample, as I cannot reproduce this issue

**Comment by akinofftz** [comment]
Just tried to commit in PhpStorm again. Yes, looks like this is not happening anymore. No idea if update of Aurelia plugin or PhpStorm solved that, but nice that I've not to use separate committing anymore. :)
