### ISSUE TITLE
Does this plugin work with latest IntelliJ (2018.2)?

### ISSUE THREAD

**Issue by seagullmouse** [denofevil/AureliaStorm#31]
I think the linking between view (html) files and view-model (.ts) files is broken with 2018.2.

Symptoms
- Methods in view are no longer underlined, and don't link through to the view model
- IntelliJ inspections think most of the my view-model is unused, e.g. "unused global symbol"

E.g. Something like
in view...
`<button click.delegate="doSomething()>Click me</button>`

in view-model...
`export class Page1{
doSomething(){
alert(1);
}
}`

**Comment by denofevil** [comment]
I was until now 😊
Can you provide a small sample project to test?

**Comment by seagullmouse** [comment]
Can anyone confirm if they have the plugin working in 2018.2.X?

I had to rollback to 2018.1 to get this working.

I appreciate I still haven't had time to provide a sample project for this yet.
