### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by mroeling** [denofevil/AureliaStorm#32]
I think it can be very valuable for the Aurelia community to improve the support for the plugin. 

What steps are necessary to create a custom build of this plugin? (if any)
Is there SDK / developer documentation available from PhpStorm? Is that http://www.jetbrains.org/intellij/sdk/docs/basics.html?

**Comment by denofevil** [comment]
Thanks a lot for your interest!

No extra steps are necessary; this project is built using [gradle-intellij-plugin](https://github.com/JetBrains/gradle-intellij-plugin), so all you need to run the plugin is to open `build.gradle` in IntelliJ and start `runIde` task.

Platform documentation is available at the mentioned link, however, it doesn't cover JS/TS APIs that most likely will be required for development. For such APIs you can take a look at the examples: [Angular plugin](
https://github.com/JetBrains/intellij-plugins/tree/master/AngularJS), [Vue plugin](
https://github.com/JetBrains/intellij-plugins/tree/master/vuejs) or ping me directly, I'd be happy to help.

**Comment by mroeling** [comment]
Is it possible with phpstorm? Or another program? I don't have access to IntelliJ...

**Comment by denofevil** [comment]
You can download [IntelliJ Community](https://www.jetbrains.com/idea/download/), it's free and should be enough

**Comment by mroeling** [comment]
Right! I'll give it a shot. Thanks!

**Comment by anstarovoyt** [comment]
Now we have a detailed tutorial https://blog.jetbrains.com/webstorm/2021/09/building-a-plugin-for-webstorm-part-1/ so I am closing the issue.
