### ISSUE TITLE
Plugin incompatible with recent versions of IntelliJ

### ISSUE THREAD

**Issue by seagullmouse** [denofevil/AureliaStorm#33]
_This is a reopening of issue #31 with further information_.

As requested I have tested with a minimal Aurelia project.

Steps to reproduce
1. Download IntelliJ 2018.1.6 and IntelliJ 2018.3.2
2. Clone the `app-contacts` project from `https://github.com/aurelia/app-contacts`
3. Create a new project with from the `app-contacts` folder in IntelliJ
4. Open the file `contact-list.html` 

**IntelliJ 2018.1.6**
![screenshot 2018-12-31 at 16 37 05](https://user-images.githubusercontent.com/1561613/50564243-569e3e00-0d1b-11e9-947f-c54bf939aec2.png)
The properties are correctly highlighted (notice the purple colour) and can be clicked Cmd-Clicked to go to the property definition in the view-model.

**IntelliJ 2018.3.2**
![screenshot 2018-12-31 at 16 30 44](https://user-images.githubusercontent.com/1561613/50564260-82b9bf00-0d1b-11e9-855a-e38db2ccb15b.png)

The properties are not highlighted (notice the normal font colour) and cannot be clicked Cmd-Clicked.
IntelliJ marks the properties as unused within the view-model.

**Comment by denofevil** [comment]
@seagullmouse thank you for the repro, I've fixed the issue, update will be available soon

**Comment by seagullmouse** [comment]
@denofevil This is an issue again with version 2019.2
