### ISSUE TITLE
2021.1 Compatibility

### ISSUE THREAD

**Issue by elitastic** [denofevil/AureliaStorm#39]
@denofevil, could you please update the plugin to support Rider 2021.1? Thank you.

**Comment by CollinHerber** [comment]
It is working for me in IntelliJ 2021.1

**Comment by elitastic** [comment]
I assume it only works cause it's doing an automatic downgrade to version 0.8.1!

see https://plugins.jetbrains.com/plugin/8567-aureliastorm/versions

**Comment by anstarovoyt** [comment]
added compatible with 2022.1 version, made old versions (e.g. 0.8.1) incompatible with new builds.
