### ISSUE TITLE
High CPU Utilization since 0.2

### ISSUE THREAD

**Issue by eikaramba** [denofevil/AureliaStorm#8]
I upgraded to version 0.2 and experiencing a constant high cpu usage(~20-40%) among .js files. Also the cursor is not responding anymore every few seconds. If a regular file is open/active, the cpu utilization is normal. I just deactivated the plugin and now it is back to normal. Can i anyhow give you some logs or so? I the normal logs accessible from the help menu i wasn't able to find anything particular interesting.

**Comment by denofevil** [comment]
@eikaramba you can capture CPU snapshot as described [here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems)

**Comment by eikaramba** [comment]
thx for that. i activated the cpu profiling, but now after reactivating it does not happen again ;) well i can only assume the reasoning behind it. but i will definitely keep an eye on it and as soon as i experience something like that again will provide a cpu profile.
